[theme]
base = "light"
primaryColor = "#2F567E"
backgroundColor = "#F0F2F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2A3742"
font = "sans serif"

[server]
maxUploadSize = 50
headless = true
